/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void start_test(GButton source, GEvent event) { //_CODE_:start_button:264212:
  println("start_button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:start_button:264212:

public void stop_test(GButton source, GEvent event) { //_CODE_:stop_button:289303:
  println("stop_button - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:stop_button:289303:

public void position_x(GTextField source, GEvent event) { //_CODE_:x_input:564070:
  println("x_input - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:x_input:564070:

public void speed_x(GTextField source, GEvent event) { //_CODE_:dx_input:359420:
  println("dx_input - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:dx_input:359420:

public void freq_x(GTextField source, GEvent event) { //_CODE_:freq_input:544729:
  println("freq_input - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:freq_input:544729:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  start_button = new GButton(this, 100, 240, 80, 30);
  start_button.setText("Start");
  start_button.setTextBold();
  start_button.addEventHandler(this, "start_test");
  stop_button = new GButton(this, 310, 240, 80, 30);
  stop_button.setText("Stop");
  stop_button.setTextBold();
  stop_button.addEventHandler(this, "stop_test");
  x_input = new GTextField(this, 60, 140, 100, 30, G4P.SCROLLBARS_NONE);
  x_input.setPromptText("Delta X");
  x_input.setOpaque(false);
  x_input.addEventHandler(this, "position_x");
  dx_input = new GTextField(this, 155, 171, 160, 30, G4P.SCROLLBARS_NONE);
  dx_input.setOpaque(true);
  dx_input.addEventHandler(this, "speed_x");
  freq_input = new GTextField(this, 276, 125, 160, 30, G4P.SCROLLBARS_NONE);
  freq_input.setOpaque(true);
  freq_input.addEventHandler(this, "freq_x");
}

// Variable declarations 
// autogenerated do not edit
GButton start_button; 
GButton stop_button; 
GTextField x_input; 
GTextField dx_input; 
GTextField freq_input; 
